[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pentest-toolbox"
version = "0.1.0"
authors = [{name = "Niklas Larsson", email = "niklas.erik.larsson@gmail.com"}]
description = "My collection of tools for Pentesting"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.6"

dependencies = [
	"progressbar2 >= 4.3.2"
]

[project.urls]
repository = "https://github.com/GroundWaIker/pentest-toolbox"
documentation = "https://github.com/GroundWaIker/pentest-toolbox/readme.md"

[project.scripts]
pentest = "pentest.main:main"
portscan = "pentest.portscan:main"
